apiVersion: homelab.mortenolsen.pro/v1
kind: OidcClient
metadata:
  name: '{{ .Release.Name }}'
spec:
  environment: '{{ .Values.globals.environment }}'
  redirectUris:
    - path: /api/auth/oidc/callback
      subdomain: '{{ .Values.subdomain }}'
      matchingMode: strict
